# Application name and server port
spring:
  application:
    name: Auth
  data:
    mongodb:
      uri: mongodb+srv://ibouderoua63:QBwjZ1zUXho1Yd0M@cluster0.hriid.mongodb.net/PigeonSkyRace?retryWrites=true&w=majority

# Server Configuration
server:
  port: 8081

# JWT configuration
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007a
    issuer: Book Store API
